$defaults:
  ENV: development
  IP: localhost
  PORT: 3001
  MURL: mongodb://localhost/dev-omnis

config:
  server:
    ip: "#{IP}"
    port: "#{PORT}"
    secret: "secret code"
    cookie:
      path: '/'
      httpOnly: true
      maxAge: 604800
  db:
    url: "#{MURL}"
  plugins:
    - session#MongoSession
    - Static
    - Less